"""add todos table

Revision ID: a284decc39f6
Revises: f25650d6b6f7
Create Date: 2026-07-28 13:36:38.191508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a284decc39f6"
down_revision: Union[str, Sequence[str], None] = "f25650d6b6f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "todo",
                "in_progress",
                "done",
                "cancelled",
                name="todo_status",
                native_enum=False,
                length=20,
            ),
            server_default="todo",
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "urgent",
                name="todo_priority",
                native_enum=False,
                length=10,
            ),
            server_default="medium",
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (status = 'done' AND completed_at IS NOT NULL)\n            OR\n            (status <> 'done' AND completed_at IS NULL)\n            ",
            name=op.f("ck_todos_completion_state"),
        ),
        sa.CheckConstraint("char_length(trim(title)) > 0", name=op.f("ck_todos_title_not_blank")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_todos_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_todos")),
    )
    op.create_index("ix_todos_user_archived", "todos", ["user_id", "is_archived"], unique=False)
    op.create_index("ix_todos_user_due_at", "todos", ["user_id", "due_at"], unique=False)
    op.create_index("ix_todos_user_status", "todos", ["user_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_todos_user_status", table_name="todos")
    op.drop_index("ix_todos_user_due_at", table_name="todos")
    op.drop_index("ix_todos_user_archived", table_name="todos")
    op.drop_table("todos")
    # ### end Alembic commands ###
