"""Add refresh-session rotation safety fields

Revision ID: d0bf5b40031b
Revises: d72c03a55ac1
Create Date: 2026-07-27 15:24:47.775305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d0bf5b40031b"
down_revision: Union[str, Sequence[str], None] = "d72c03a55ac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_sessions", sa.Column("previous_token_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "refresh_sessions",
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "refresh_sessions", sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "ix_refresh_sessions_absolute_expires_at",
        "refresh_sessions",
        ["absolute_expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refresh_sessions_absolute_expires_at", table_name="refresh_sessions")
    op.drop_column("refresh_sessions", "rotated_at")
    op.drop_column("refresh_sessions", "absolute_expires_at")
    op.drop_column("refresh_sessions", "previous_token_hash")
    # ### end Alembic commands ###
