"""add oauth authorization codes

Revision ID: e370ad374584
Revises: a284decc39f6
Create Date: 2026-08-01 10:17:26.259122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e370ad374584"
down_revision: Union[str, Sequence[str], None] = "a284decc39f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_authorization_codes",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("code_challenge", sa.String(length=43), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "char_length(client_id) > 0",
            name=op.f("ck_oauth_authorization_codes_client_id_not_empty"),
        ),
        sa.CheckConstraint(
            "char_length(code_challenge) = 43",
            name=op.f("ck_oauth_authorization_codes_code_challenge_length"),
        ),
        sa.CheckConstraint(
            "char_length(code_hash) = 64",
            name=op.f("ck_oauth_authorization_codes_code_hash_length"),
        ),
        sa.CheckConstraint(
            "char_length(redirect_uri) > 0",
            name=op.f("ck_oauth_authorization_codes_redirect_uri_not_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_authorization_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("code_hash", name=op.f("pk_oauth_authorization_codes")),
    )
    op.create_index(
        "ix_oauth_authorization_codes_expires_at",
        "oauth_authorization_codes",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_user_id"),
        "oauth_authorization_codes",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_oauth_authorization_codes_user_id"), table_name="oauth_authorization_codes"
    )
    op.drop_index("ix_oauth_authorization_codes_expires_at", table_name="oauth_authorization_codes")
    op.drop_table("oauth_authorization_codes")
    # ### end Alembic commands ###
